# -*- coding: utf-8 -*-
"""AI-Powered Customer Service Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywndekVUI6qba_B4rIdqhwxBaaNT9BLC
"""

# =============================================
# PROFESSIONAL RETAIL CHATBOT (Fixed + New Chat + History + iOS Glass Theme)
# =============================================

!pip install gradio transformers sentence-transformers -q

import gradio as gr
import uuid
from sentence_transformers import SentenceTransformer, util

# Load AI Model
model = SentenceTransformer('all-MiniLM-L6-v2')

# ========== Knowledge Base ==========
knowledge_base = {
    "greeting": {
        "questions": ["hello", "hi", "hey", "good morning", "good afternoon", "namaste"],
        "response": "Hello! Welcome to SmartShop. How can I assist you today?"
    },
    "order_status": {
        "questions": ["order status", "where is my order", "track order", "delivery", "shipping"],
        "response": "To check your order status, please provide your order number. I'll track it immediately for you!"
    },
    "returns": {
        "questions": ["return", "refund", "exchange", "change mind", "wrong item"],
        "response": "We accept returns within 30 days. Please visit our returns portal or I can guide you through the process!"
    },
    "products": {
        "questions": ["products", "what do you sell", "items", "catalog", "available"],
        "response": "We sell electronics, clothing, home goods, and more! What specific product are you looking for?"
    },
    "prices": {
        "questions": ["price", "cost", "how much", "discount", "offer", "sale"],
        "response": "Our prices are competitive! Visit our website for the latest deals. I can also help with product recommendations."
    },
    "support": {
        "questions": ["support", "help", "contact", "agent", "human"],
        "response": "I'm here to help! If you need a human agent, I can connect you. Just tell me what you need."
    },
    "payment": {
        "questions": ["pay", "payment", "card", "credit", "debit", "cash", "online"],
        "response": "We accept all major credit cards, digital wallets, and cash on delivery. Secure payment is guaranteed!"
    },
    "delivery": {
        "questions": ["delivery time", "shipping time", "when will i get", "arrive", "receive"],
        "response": "Standard delivery takes 3-5 business days. Express delivery is available for 1-2 days."
    },
    "default": {
        "questions": [],
        "response": "I understand you're asking about something. Could you please rephrase? I'm here to help with orders, returns, products, and support!"
    }
}

def get_best_response(user_message):
    user_message = user_message.lower()

    # Check for exact keyword matches first
    for key, value in knowledge_base.items():
        for q in value["questions"]:
            if q in user_message:
                return value["response"]

    # If no keyword match, use default
    return knowledge_base["default"]["response"]

def chat_with_bot(message, history):
    response = get_best_response(message)

    # Add personalized touch
    if "order" in message.lower():
        response += " Please share your order number."
    elif "price" in message.lower() or "cost" in message.lower():
        response += " Check our website for current promotions!"

    return response

# =============================================
# iOS Glass Effect Theme (Dark Mode + Gradient) CSS
# =============================================
glass_css = """
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

* {
    font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Inter', sans-serif !important;
}

body, .gradio-container {
    background: linear-gradient(135deg, #0f0c29 0%, #302b63 25%, #24243e 50%, #1a1a3d 75%, #0f0c29 100%);
    background-size: 400% 400%;
    animation: gradientShift 22s ease infinite;
    min-height: 100vh;
}

@keyframes gradientShift {
    0% { background-position: 0% 50%; }
    50% { background-position: 100% 50%; }
    100% { background-position: 0% 50%; }
}

/* subtle glowing color accents behind the glass panels */
.gradio-container::before {
    content: "";
    position: fixed;
    top: -20%;
    left: -10%;
    width: 60%;
    height: 60%;
    background: radial-gradient(circle, rgba(116,185,255,0.25) 0%, transparent 70%);
    pointer-events: none;
    z-index: 0;
}

.gradio-container::after {
    content: "";
    position: fixed;
    bottom: -20%;
    right: -10%;
    width: 60%;
    height: 60%;
    background: radial-gradient(circle, rgba(253,121,168,0.2) 0%, transparent 70%);
    pointer-events: none;
    z-index: 0;
}

.glass-panel {
    background: rgba(255, 255, 255, 0.06) !important;
    backdrop-filter: blur(25px) saturate(180%) !important;
    -webkit-backdrop-filter: blur(25px) saturate(180%) !important;
    border: 1px solid rgba(255, 255, 255, 0.12) !important;
    border-radius: 22px !important;
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.35) !important;
}

#sidebar {
    background: rgba(255, 255, 255, 0.05) !important;
    backdrop-filter: blur(30px) saturate(180%) !important;
    -webkit-backdrop-filter: blur(30px) saturate(180%) !important;
    border-radius: 22px !important;
    border: 1px solid rgba(255, 255, 255, 0.12) !important;
    padding: 12px !important;
    position: relative;
    z-index: 1;
}

#new-chat-btn {
    background: linear-gradient(135deg, rgba(116,185,255,0.35), rgba(162,155,254,0.35)) !important;
    backdrop-filter: blur(20px) !important;
    border: 1px solid rgba(255, 255, 255, 0.25) !important;
    border-radius: 16px !important;
    color: #ffffff !important;
    font-weight: 600 !important;
    box-shadow: 0 4px 16px rgba(0, 0, 0, 0.3) !important;
    transition: all 0.25s ease !important;
}

#new-chat-btn:hover {
    background: linear-gradient(135deg, rgba(116,185,255,0.55), rgba(162,155,254,0.55)) !important;
    transform: translateY(-2px);
}

#chat-history-list {
    background: transparent !important;
}

#chat-history-list label {
    background: rgba(255, 255, 255, 0.06) !important;
    backdrop-filter: blur(15px) !important;
    border-radius: 14px !important;
    border: 1px solid rgba(255, 255, 255, 0.1) !important;
    margin-bottom: 6px !important;
    padding: 8px 12px !important;
    transition: all 0.2s ease !important;
    color: #f1f1f6 !important;
}

#chat-history-list label:hover {
    background: rgba(255, 255, 255, 0.14) !important;
}

#chat-history-list span {
    color: #f1f1f6 !important;
}

#chatbot-window {
    background: rgba(255, 255, 255, 0.05) !important;
    backdrop-filter: blur(25px) saturate(180%) !important;
    -webkit-backdrop-filter: blur(25px) saturate(180%) !important;
    border-radius: 22px !important;
    border: 1px solid rgba(255, 255, 255, 0.12) !important;
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.35) !important;
    position: relative;
    z-index: 1;
}

#chatbot-window .message, #chatbot-window p, #chatbot-window span {
    color: #f1f1f6 !important;
}

#chatbot-window .user, #chatbot-window .bot {
    background: rgba(255, 255, 255, 0.08) !important;
    backdrop-filter: blur(10px) !important;
    border: 1px solid rgba(255, 255, 255, 0.1) !important;
}

#msg-box textarea, #msg-box input {
    background: rgba(255, 255, 255, 0.08) !important;
    backdrop-filter: blur(15px) !important;
    border-radius: 18px !important;
    border: 1px solid rgba(255, 255, 255, 0.18) !important;
    color: #ffffff !important;
}

#msg-box textarea::placeholder, #msg-box input::placeholder {
    color: rgba(255, 255, 255, 0.55) !important;
}

/* Fixed send button: explicit size so the arrow icon renders centered
   instead of stretching into a blank pill */
#send-btn {
    background: linear-gradient(135deg, #74b9ff, #a29bfe) !important;
    backdrop-filter: blur(15px) !important;
    border-radius: 50% !important;
    border: 1px solid rgba(255, 255, 255, 0.3) !important;
    color: #ffffff !important;
    width: 48px !important;
    height: 48px !important;
    min-width: 48px !important;
    max-width: 48px !important;
    padding: 0 !important;
    flex-shrink: 0 !important;
    font-size: 20px !important;
    line-height: 1 !important;
    display: flex !important;
    align-items: center !important;
    justify-content: center !important;
    box-shadow: 0 4px 16px rgba(0, 0, 0, 0.3) !important;
    transition: all 0.25s ease !important;
}

#send-btn:hover {
    transform: scale(1.08);
    box-shadow: 0 6px 20px rgba(116, 185, 255, 0.5) !important;
}

.title-text {
    color: #ffffff !important;
    text-shadow: 0 2px 12px rgba(116, 185, 255, 0.4);
}

label, .gr-markdown, .block-title, span, p {
    color: #f1f1f6;
}
"""

# =============================================
# Multi-Chat State Logic
# =============================================

def make_new_chat_id():
    return str(uuid.uuid4())

def new_chat(chats, current_id):
    new_id = make_new_chat_id()
    chats[new_id] = {"title": "New Chat", "messages": []}
    choices = get_history_choices(chats)
    return chats, new_id, [], gr.update(choices=choices, value=new_id)

def get_history_choices(chats):
    # Newest chats first
    items = list(chats.items())
    items.reverse()
    return [(data["title"], cid) for cid, data in items]

def switch_chat(selected_id, chats):
    if selected_id is None or selected_id not in chats:
        return [], selected_id
    return chats[selected_id]["messages"], selected_id

def send_message(message, chats, current_id):
    if not message or not message.strip():
        choices = get_history_choices(chats)
        current_messages = chats.get(current_id, {}).get("messages", [])
        return current_messages, chats, current_id, gr.update(choices=choices, value=current_id), ""

    # If no active chat, create one
    if current_id is None or current_id not in chats:
        current_id = make_new_chat_id()
        chats[current_id] = {"title": "New Chat", "messages": []}

    response = chat_with_bot(message, chats[current_id]["messages"])

    chats[current_id]["messages"].append({"role": "user", "content": message})
    chats[current_id]["messages"].append({"role": "assistant", "content": response})

    # Auto-title the chat from the first user message
    if chats[current_id]["title"] == "New Chat":
        short_title = message.strip()
        if len(short_title) > 28:
            short_title = short_title[:28] + "..."
        chats[current_id]["title"] = short_title

    choices = get_history_choices(chats)
    return chats[current_id]["messages"], chats, current_id, gr.update(choices=choices, value=current_id), ""


# =============================================
# Build Interface
# =============================================
with gr.Blocks(title="SmartShop AI Assistant") as iface:

    chats_state = gr.State({})
    current_chat_id = gr.State(None)

    gr.Markdown("<h1 class='title-text' style='text-align:center;'>SmartShop AI Assistant</h1>"
                "<p class='title-text' style='text-align:center;'>Your 24/7 Virtual Shopping Assistant</p>")

    with gr.Row():
        with gr.Column(scale=1, elem_id="sidebar"):
            new_chat_btn = gr.Button("+ New Chat", elem_id="new-chat-btn")
            gr.Markdown("<p class='title-text' style='margin-top:10px;'>Chat History</p>")
            chat_history_list = gr.Radio(
                choices=[],
                label=None,
                elem_id="chat-history-list",
                show_label=False,
                container=False
            )

        with gr.Column(scale=3):
            chatbot = gr.Chatbot(
                elem_id="chatbot-window",
                height=520,
                show_label=False
            )
            with gr.Row():
                msg = gr.Textbox(
                    placeholder="Type a message...",
                    show_label=False,
                    scale=8,
                    elem_id="msg-box"
                )
                send_btn = gr.Button("➤", scale=1, elem_id="send-btn")

            gr.Examples(
                examples=[
                    ["Hello! Do you have any promotions?"],
                    ["Can I check my order status?"],
                    ["How do I return a product?"],
                    ["What products do you sell?"],
                    ["I need help with payment"],
                    ["When will my order arrive?"]
                ],
                inputs=msg
            )

    # Wire up events
    new_chat_btn.click(
        new_chat,
        inputs=[chats_state, current_chat_id],
        outputs=[chats_state, current_chat_id, chatbot, chat_history_list]
    )

    chat_history_list.change(
        switch_chat,
        inputs=[chat_history_list, chats_state],
        outputs=[chatbot, current_chat_id]
    )

    msg.submit(
        send_message,
        inputs=[msg, chats_state, current_chat_id],
        outputs=[chatbot, chats_state, current_chat_id, chat_history_list, msg]
    )

    send_btn.click(
        send_message,
        inputs=[msg, chats_state, current_chat_id],
        outputs=[chatbot, chats_state, current_chat_id, chat_history_list, msg]
    )

iface.launch(share=True, css=glass_css)